version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-land_registry}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  indexer:
    build: .
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-land_registry}
      - LAND_REGISTRY_ADDRESS=${LAND_REGISTRY_ADDRESS}
      - STARTING_BLOCK=${STARTING_BLOCK:-0}
      - APIBARA_URL=${APIBARA_URL}
    depends_on:
      - postgres

volumes:
  postgres_data: 